@startuml AddLavController
!theme vibrant
hide footbox
mainframe Add Lavoratore
participant Actor
Actor -> AddLavController : Lavoratore Data\nEmergenza Data
activate AddLavController

AddLavController -> Lavoratore : << create >> \nLavoratore Data
activate Lavoratore
Lavoratore --> AddLavController : Lavoratore
deactivate Lavoratore

AddLavController -> LavoratoreRepo : addLavoratore(Lavoratore)
activate LavoratoreRepo
LavoratoreRepo --> AddLavController : id_lav = ID Lavoratore
deactivate LavoratoreRepo

AddLavController -> Emergenza : << create >> \nEmergenza Data
activate Emergenza
Emergenza --> AddLavController : Emergenza
deactivate Emergenza

AddLavController -> EmergenzaRepo : addEmergenza(id_lav, Emergenza)
AddLavController --> DataRepo : setLavoratoreID(id_lav)
AddLavController -> ViewLoader : loadView(MODIFICA_LAVORATORE)
activate ViewLoader
ViewLoader --> Actor : View
deactivate ViewLoader
@enduml