@startuml initialize
!theme vibrant
hide footbox
participant Actor

Actor -> AddLavController : loadView
activate AddLavController
AddLavController -> DataRepo : getDipendente
activate DataRepo
DataRepo --> AddLavController
deactivate DataRepo
AddLavController -> Dipendente : getId
activate Dipendente
Dipendente --> AddLavController
deactivate Dipendente
AddLavController -> DataRepo : isViewMode
activate DataRepo
DataRepo --> AddLavController
deactivate DataRepo
AddLavController -> DataRepo : getLavoratore_id
activate DataRepo
DataRepo --> AddLavController
deactivate DataRepo
return
@enduml