@startuml LoginController
!theme vibrant
mainframe Login
hide footbox
participant Actor
Actor -> LoginController : user,password
activate LoginController
LoginController -> DipendenteRepo : getDipendenteByUserAndPassword(user,password)
activate DipendenteRepo
activate DipendenteRepo 
alt #LightGreen Successful login
    DipendenteRepo --> LoginController: Dipendente
    deactivate DipendenteRepo
    LoginController -> DataRepo : setDipendente(Dipendente)
    LoginController -> ViewLoader : loadView(MENU)
    ViewLoader --> Actor: View
else #Pink  Failed login
    DipendenteRepo --> LoginController: NULL
    deactivate DipendenteRepo
    LoginController --> Actor: Wrong User or Password
    deactivate LoginController
end
@enduml