@startuml SearchController
!theme vibrant
hide footbox
participant Actor
Actor -> SearchController : addDataToFilter
activate SearchController
alt Data is valid 
SearchController -> FilterBuilder : addFilter
SearchController -> FilterBuilder : readableString
activate FilterBuilder
FilterBuilder --> SearchController
deactivate FilterBuilder
SearchController --> Actor : Readable SQL String
else data invalid
SearchController --> Actor : Invalid data
deactivate SearchController
end
@enduml